### ISSUE TITLE
Multiple Bundles

### ISSUE THREAD

**Issue by rawcreative** [skrajewski/laravel-elixir-browserify#12] opened 2015-02-11 16:37 UTC
As it stands right now, it's not possible to create multiple bundles, since multiple mix.browserify() calls only actually bundles the last call. 

To get around this I refactored the plugin to allow for passing multiple bundle configs as the src param. This works, but it's kinda hacky, and it would work much better if the plugin only required a single param (which could optionally be an array of configs) instead of the current: src, options. 

I can submit a PR with either method if you'd like, the current way is backwards compatible, the latter (but better) method would be a breaking change.. thoughts?

**Comment by skrajewski** [comment] 2015-02-12 23:21
Hi @rawcreative,

I want to see your solutions, if you can please make fork or send me PR.

Many thanks!

**Comment by Daveawb** [comment] 2015-02-17 08:09
To function correctly IMO a change needs to be made to elixirs core. Currently if it notices that an ingredient is a duplicate of one already registered in the execution stack it replaces the old with the new. There needs to be a configure option to stop this as it'd be better to create two separate browserify mixes. I'm working on a PR to core at the moment to solve this.

**Comment by devinfd** [comment] 2015-02-27 18:28
Couldn't laravel-elixir-browserify accept an array as the first argument and loop/browserify through each value?

**Comment by skrajewski** [comment] 2015-02-27 22:48
Theoretically it's possible, but it introduces more complex logic to this extension. In my opinion the better solution is twice call browserify() in mix, but currently it's not supported.

**Comment by devinfd** [comment] 2015-02-28 20:03
You say its better to twice call browserify(), but what if there were more than 2 bundles that needed to be created? Perhaps the array option is an acceptable solution until a better solution becomes available.

**Comment by rawcreative** [comment] 2015-02-28 21:28
I've just submitted a pull request with this functionality, see: https://github.com/skrajewski/laravel-elixir-browserify/pull/15

**Comment by Daveawb** [comment] 2015-03-07 21:07
I submitted https://github.com/skrajewski/laravel-elixir-browserify/pull/17 this morning that allows multiple bundles to be made with:

```javascript
mix.browserify("bootstrap.js")
    .browserify("second_bundle")
    .browserify("another_bundle");
```

**Comment by skrajewski** [comment] 2015-03-14 21:28
Done by #18

**Closed by skrajewski** 2015-03-14 21:28 UTC
